name: "kplanes_refine"
tag: "${data.random_camera.height}_${rmspace:${basename:${data.image_path}},_}_${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "multiview-camera-datamodule"
data:
  train_downsample_resolution: 1
  eval_downsample_resolution: 1
  n_views: 4
  dataroot: ???
  camera_layout: "input"
  use_random_camera: True
  random_camera: # threestudio/data/svd_uncond.py -> SVDDataModuleConfig
    height: [128, 128, 128] # [72, 72, 72]
    width: [128, 128, 128] # [72, 72, 72]
    batch_size: [21, 21, 21] # same as video model # of frames
    resolution_milestones: [600, 700]
    eval_height: 512
    eval_width: 512
    eval_batch_size: 1
    elevation_range: [-10, 80]
    azimuth_range: [-180, 180]
    camera_distance_range: [3.5, 3.5]
    fovy_range: [20.0, 20.0] # Zero123 has fixed fovy
    progressive_until: 0
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    light_position_perturb: 1.0
    light_distance_range: [7.5, 10.0]
    eval_elevation_deg: 5.0 # ${data.default_elevation_deg}
    eval_camera_distance: 3.5 # ${data.default_camera_distance}
    eval_fovy_deg: 33.9 # 20.0 # ${data.default_fovy_deg}
    light_sample_strategy: "dreamfusion"
    batch_uniform_azimuth: False
    n_train_views: 21
    n_val_views: 21
    n_test_views: 126

system_type: "magic123-system"
system:
  refinement: true
  geometry_convert_from: "implicit-volume"
  # geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 128
    isosurface_deformable_grid: true
    pos_encoding_config:
      otype: KPlanes
      n_feature_count: 32
      resolutions: [128, 256, 512]     # each entry N in this list creates K planes with resolution N x N.
      n_dimensions: 3            # 3 => 3 planes per resolution, 4 => 6 planes per resolution
    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 64
      n_hidden_layers: 1
    fix_geometry: false # optimize grid sdf and deformation

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 0
    textureless_prob: 0.05
    albedo_activation: sigmoid

  background_type: "solid-color-background"
  background:
    random_aug_prob: 0.5
    random_aug: true

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda
  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: "" # ???

  guidance_type: "svd-guidance"
  guidance:
    stable_research_path: "/weka/home-chunhanyao/stable-research" # "/admin/home-vikram/ROBIN/stable-research"
    pretrained_model_name_or_path: "prediction_3D_OBJ_SVD21V" # "prediction_stable_jucifer_3D_OBJ_IMG"
    cond_aug: 0.00
    num_steps: 50
    height: 512 # ${max:${data.random_camera.height}}
    vram_O: true
    cond_image_path: ${data.dataroot}
    cond_img_height: 512
    cond_elevation_deg: 5.0 # ${data.default_elevation_deg}
    cond_azimuth_deg: 0 # ${data.default_azimuth_deg}
    cond_camera_distance: 3.5 # ${data.default_camera_distance}
    guidance_scale: 4.0
    min_step_percent: 0.3
    max_step_percent: 0.8
    noises_per_item: 1
    guidance_eval_freq: 0

  loss:
    lambda_rgb: 1000.
    lambda_mask: 100.
    lambda_sds: 0.1
    # lambda_sd: 0.025
    # lambda_3d_sd: 1.
    lambda_normal_consistency: 1000.
    lambda_laplacian_smoothness: 0.
    lambda_lpips: 200.0

  optimizer:
    name: Adam
    args:
      lr: 0.005
      betas: [0.9, 0.99]
      eps: 1.e-8

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 500
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
